! git add .
! git commit -m "Archivos creados"
! git push

In [61]:
! git add .
! git commit -m "5to ejercicio hecho"
! git push

[main bbc3609] 4to ejercicio hecho
 1 file changed, 36 insertions(+), 2 deletions(-)


To https://github.com/Senryo1/laboratorio-3.git
   eaa82cb..bbc3609  main -> main


Parte 1: Numpy:
Para los ejercicios siguiente genere el código que considere
para resolver el problema que se le plantea.
1) ¿Cuál es el tamaño en bytes de un array de 1000
elementos de tipo booleano?

In [7]:
import numpy as np

# Creamos un array de booleanos con 1000 elementos
arr = np.random.choice([True, False], size=1000)

# Obtenemos el tamaño en bytes del array
size = arr.nbytes

print("El tamaño en bytes del array de 1000 elementos de tipo booleano es:", size)

El tamaño en bytes del array de 1000 elementos de tipo booleano es: 1000


2) Cree un array cuyos elementos sean los enteros pares en
[1,100] y en orden decreciente. Muestre los 10 últimos
por pantalla.

In [16]:
import numpy as np
arr = np.arange(100, 0, -2)
ultimos10 = arr[-10:]
print(ultimos10)

[20 18 16 14 12 10  8  6  4  2]


3) Dado el array
2 4 5 6
0 3 7 4
8 8 5 2
1 5 6 1
Seleccione con una instrucción el subarray de elementos
0 3 7 4
Después, seleccione el subarray de elementos
2 5
8 5

In [54]:
import numpy as np
arr = np.array([[2, 4, 5, 6],
                [0, 3, 7, 4],
                [8, 8, 5, 2],
                [1, 5, 6, 1]])
print(arr[1])
# Creamos una máscara booleana para los números 2, 5 y 8
print(arr[[0, 2], [0, 2]])
print(arr[[2, 2], [0, 2]])

[0 3 7 4]
[2 5]
[8 5]


4) Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9],
obtenga la media aritmética de la diferencia (a-b)

In [59]:
import numpy as np
arr = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])
resta = arr-b
media = np.mean(resta)
resta

array([ 0,  1,  0, -2])

5) Tengo valores de cordenadas (x, y) en las columnas
del array
1.33 4.5
30.0 10.7
70.2 0.5
Agregue a este array las coordenadas (37.1, -3.6).
Muestre en pantalla las dimensiones del nuevo
array

In [6]:
import numpy as np
arr = np.array([[1.33,4.5]
,[30.0,10.7]
,[70.2,0.5]])
print(arr)
arr1 = np.append(arr,[[37.1, -3.6]],axis = 0)
arr1

[1 2 3 4 5 6]


[[ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]]


array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ]])